#if !canImport(ObjectiveC)
import XCTest

extension BrotliJSONDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BrotliJSONDecoderTests = [
        ("testDecode", testDecode),
    ]
}

extension BrotliJSONEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BrotliJSONEncoderTests = [
        ("testEncode", testEncode),
    ]
}

extension BrotliTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BrotliTests = [
        ("testCompress", testCompress),
        ("testCompressWithModeText", testCompressWithModeText),
        ("testDecompress", testDecompress),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BrotliJSONDecoderTests.__allTests__BrotliJSONDecoderTests),
        testCase(BrotliJSONEncoderTests.__allTests__BrotliJSONEncoderTests),
        testCase(BrotliTests.__allTests__BrotliTests),
    ]
}
#endif
